.\"
.\" dis8080 - Intel 8080 disassembler
.\"
.\" Copyright (c) 2020 Brian Callahan <bcallah@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 16, 2020
.Dt DIS8080 1
.Os
.Sh NAME
.Nm dis8080
.Nd Intel 8080 disassembler
.Sh SYNOPSIS
.Nm
.Ar file
.Op Ar count
.Op Ar offset
.Sh DESCRIPTION
.Nm
is a disassembler for the Intel 8080 CPU.
It reads in an Intel 8080 executable
.Ar file
and outputs the assembly instructions of that executable to
.Ar stdout .
.Pp
If
.Ar count
is issued on the command line, print that many lines of instructions.
The
.Ar count
argument is understood as hexadecimal.
Defaults to 7.
.Pp
If
.Ar offset
is issued on the command line, disassembly begins at the memory
offset specified.
The
.Ar offset
argument is understood as hexadecimal.
Defaults to 100h.
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh EXAMPLES
Read an Intel 8080 executable named
.Ar hello.com ,
print
.Ar 11
instructions, and begin at offset
.Ar 200h :
.Pp
.Dl dis8080 hello.com b 200
.Pp
Print the entire disassembly of
.Ar hello.com :
.Pp
.Dl dis8080 hello.com ffff
.Sh AUTHORS
.Nm
was written by
.An Brian Callahan Aq Mt bcallah@openbsd.org .
.Sh CAVEATS
The
.Ar count
argument cannot be issued unless the
.Ar offset
argument is also issued.
.Sh BUGS
If the user specifies an incorrect
.Ar offset ,
.Nm
will display addresses that will be incorrect.
The default
.Ar offset
will work for most standard CP/M binaries.
