.\"
.\" rpn - Reverse Polish notation calculator
.\"
.\" Copyright (c) 2020 Brian Callahan <bcallah@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 16, 2020
.Dt RPN 1
.Os
.Sh NAME
.Nm rpn
.Nd Reverse Polish notation calculator
.Sh SYNOPSIS
.Nm
.Ar expression
.Sh DESCRIPTION
.Nm
is a Reverse Polish notation calculator.
.Nm
reads in an
.Ar expression
written on the command line and outputs the answer to
.Ar stdout .
.Pp
.Nm
accepts the following operators:
.Bl -tag -width Ds
.It +
Addition
.It -
Subtraction
.It x
Multiplication
.It /
Division
.It %
Modulo
.El
.Pp
All operands and operators must be separated by whitespace.
.Pp
All operands and results are interpreted as decimal numbers.
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh AUTHORS
.Nm
was written by
.An Brian Callahan Aq Mt bcallah@openbsd.org .
.Sh CAVEATS
.Nm
does not accept parentheses.
Users must format
.Ar expression
to avoid the need for parentheses.
.Sh BUGS
.Nm
cannot accept negative numbers directly.
Input
.Sy 0 x -
to get
.Sy -x .
.Pp
.Nm
has a maximum stack size of 512 32-bit signed integers.
